/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproject;
import java.sql.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
/**
 *
 * @author Admin
 */
public class Main_Window extends javax.swing.JFrame implements ActionListener{

    javax.swing.JRadioButton r[];
    
    //JLabel arrays
    javax.swing.JLabel l[];
    javax.swing.JLabel l_names[];
    javax.swing.JLabel l_status[];
    javax.swing.JLabel l_price[];
    javax.swing.JLabel l_type[];
    javax.swing.JLabel l_address[];
    
    //JButton array
    javax.swing.JButton b_view[];
    
    //JPanel array
    javax.swing.JPanel jPanel_arr[];
    
    String city[]={" "};
    
    //String arrays
    String arr_names[];
    String arr_status[];
    String arr_price[];
    String arr_type[];
    String arr_address[];
    int arr_id[];

    //variables
    int total;
    
    Connection con=null;
    ResultSet rs=null;
    /**
     * Creates new form Main_Window
     */

    int userID;
    String userName;
    public Main_Window(int uid)
    {
        userID=uid;
       
        initComponents();
        
        jPanel7.setLayout(new java.awt.GridLayout(0,1,5,5));
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        try{
            //variables
            int i=0,j=0;
            
            
            
            //URL icon=getClass().getResource("/resources/search.png");
            //Icon search=new ImageIcon(icon);
            
            //Used to increase the scrolling spped of scrollpane
            jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
                             
            
            con=DBconnection.connect();
            Statement stmt = con.createStatement();
            
            ResultSet rs0=stmt.executeQuery("select User_name from user where User_id="+uid+";");  
    
            rs0.next();
            
            usernm.setText(usernm.getText()+" "+String.valueOf(rs0.getString(1))+"!");
            //Get count of distinctive property address to initialize city array
            ResultSet rs=stmt.executeQuery("select COUNT(DISTINCT Property_Address) from property;");  
            rs.next();
            i=rs.getInt(1);
            city=new String[i];
            
            //slecting unique property address from database to assign it to combobox
            ResultSet rs1=stmt.executeQuery("select DISTINCT Property_Address from property;");
            j=0;
            while(rs1.next()){
                city[j]=String.valueOf(rs1.getString(1));
                j++;
            }
            
            ResultSet rs2=stmt.executeQuery("select COUNT(Property_id) from property;");  
            rs2.next();
           
            jLabel7.setText(jLabel7.getText()+" \n"+String.valueOf(rs2.getInt(1)));
            
            ResultSet rs3=stmt.executeQuery("select COUNT(Property_id) from property where User_id ="+uid+";");  
            rs3.next();
           
            jLabel8.setText(jLabel8.getText()+" \n"+String.valueOf(rs3.getInt(1)));
            
            ResultSet rs4=stmt.executeQuery("select COUNT(DISTINCT Property_Address) from property;");  
            rs4.next();
           
            jLabel9.setText(jLabel9.getText()+" \n"+String.valueOf(rs4.getInt(1)));

            //setting the unique address to combobox1 in bottom left corner
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(city));
                                  
            con.close();  
                                    
        }
        catch(Exception e){
            System.out.println(e);
        }
        start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usernm = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(27, 98, 117));

        jPanel2.setBackground(new java.awt.Color(27, 98, 117));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(27, 98, 117));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jPanel3.setBackground(new java.awt.Color(27, 98, 117));

        jRadioButton4.setBackground(new java.awt.Color(27, 98, 117));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("<25000");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(27, 98, 117));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("< 1000");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(27, 98, 117));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("<10000");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(27, 98, 117));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("< 5000");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filter By Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)))
                    .addComponent(jLabel1))
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filter Options");

        jPanel4.setBackground(new java.awt.Color(27, 98, 117));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(city));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filter By Location");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Show all");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total properties available:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Your properties:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Locations available:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(37, 37, 37)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)))))
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addGap(23, 23, 23)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setLayout(null);

        jButton4.setText("jButton4");
        jPanel6.add(jButton4);
        jButton4.setBounds(1, 1, 73, 23);

        jLabel5.setText("jLabel5");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(74, 1, 73, 23);

        jPanel7.setBackground(new java.awt.Color(27, 98, 117));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel7);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("--");

        usernm.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        usernm.setForeground(new java.awt.Color(255, 255, 255));
        usernm.setText("Hi");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Private Property Rental System");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operations", "Profile", "Add property", "Update property", "Remove property", "View History", "Log-out" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(usernm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox2, 0, 102, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(74, 74, 74)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usernm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{

            start();

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        int total=0;
        String location = String.valueOf(jComboBox1.getSelectedItem());
        System.out.println(location);
        total=initialize_arrays(0,location,"",2);

        property_details(0,location,"",2);

        set_jpanel7(total);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        // TODO add your handling code here:
        total=0;
        try{

            total=initialize_arrays(5000,"","",1);

            property_details(5000,"","",1);

            set_jpanel7(total);

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
        // TODO add your handling code here:
        total=0;
        try{

            total=initialize_arrays(10000,"","",1);

            property_details(10000,"","",1);

            set_jpanel7(total);

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        total=0;
        try{

            total=initialize_arrays(1000,"","",1);

            property_details(1000,"","",1);

            set_jpanel7(total);

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
        // TODO add your handling code here:
        total=0;
        try{

            total=initialize_arrays(25000,"","",1);

            property_details(25000,"","",1);

            set_jpanel7(total);

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String search=jTextField1.getText();
        total=0;
        total=initialize_arrays(0,"",search,3);
        property_details(0,"",search,3);
        set_jpanel7(total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == ItemEvent.SELECTED) {
        //Do any operations you need to do when an item is selected.
        String operation = String.valueOf(jComboBox2.getSelectedItem());
        
            switch(operation){
                case "Profile":
                    setVisible(false);
                    //this.dispose();
                    Profile_page pp=new Profile_page(userID);
                    pp.setLocationRelativeTo(null);
                    pp.setVisible(true);
                    pp.setDefaultCloseOperation(HIDE_ON_CLOSE);
                   break;
                case "Add property":

                    setVisible(false);
                    InsertProperty ip=new InsertProperty();
                    ip.setLocationRelativeTo(null);
                    ip.setVisible(true);
                    ip.setDefaultCloseOperation(HIDE_ON_CLOSE);
                    break;
                    
                case "Update property":

                    setVisible(false);
                    UpdateProperty up1=new UpdateProperty(userID);
                    up1.setLocationRelativeTo(null);
                    up1.setVisible(true);
                    up1.setDefaultCloseOperation(HIDE_ON_CLOSE);
                    break;
                case "Remove property":
                    setVisible(false);
                    //this.dispose();
                    deleteproperty d1=new deleteproperty(userID);
                    d1.setLocationRelativeTo(null);
                    d1.setVisible(true);
                    d1.setDefaultCloseOperation(HIDE_ON_CLOSE);
                   break;
                case "View History":
                    setVisible(false);
                    //this.dispose();
                    Rentalhistory rh=new Rentalhistory(userID);
                    rh.setLocationRelativeTo(null);
                    rh.setVisible(true);
                    rh.setDefaultCloseOperation(HIDE_ON_CLOSE);

                    break;
                case "Log-out":
                    this.dispose();
                    MainPropertySystem mps=new MainPropertySystem();
                    mps.setLocationRelativeTo(null);
                    mps.setVisible(true);
                    break;
                default:
                    break;
            }
        }
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        MainPropertySystem mps=new MainPropertySystem();
        mps.setLocationRelativeTo(null);
        mps.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
//
    
    //method is retrive and display all the available properties
    public void start(){
        total=0;
        total=initialize_arrays(0,"","",0);
        property_details(0,"","",0);
        set_jpanel7(total);
    }
    public int initialize_arrays(int price,String location,String search,int code){
        //note: code variable is used to decide which query to excute
        //code=0 select all records
        //code=1 select records based on price
        //code=2 select records based on location
        //code=3 select records based on search term
        
        //variables
        int total_records=0;
        ResultSet rs=null;
        
        try{
        //Class.forName("com.mysql.cj.jdbc.Driver");
        //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/privatepropertyrentalsystemdb", "shivani", "root");
        con=DBconnection.connect();
        Statement stmt = con.createStatement();
        
            //checking whcih query to excute based on code passed
            if(code==0){
                rs=stmt.executeQuery("select COUNT(Property_id) from property;");
            }
            else if(code==1){
                rs=stmt.executeQuery("select COUNT(Property_id) from property where Rental_price < "+price+";");
            }
            else if(code==2){
                rs=stmt.executeQuery("select COUNT(Property_id) from property where Property_address = '"+location+"';");
            }
            else if(code==3){
                 rs=stmt.executeQuery("select COUNT(Property_id) from property where Property_name like '"+search+"%' OR Property_address like '"+search+"%' OR Rental_price like '"+search+"%';");
            }
            rs.next();
            total_records=rs.getInt(1);
            
            //Initializing label arrays as per no. of properties
            l_names=new javax.swing.JLabel[total_records];
            l_status=new javax.swing.JLabel[total_records];
            l_price=new javax.swing.JLabel[total_records];
            l_type=new javax.swing.JLabel[total_records];
            l_address=new javax.swing.JLabel[total_records];
 
            b_view=new javax.swing.JButton[total_records];
            
            //Initializing new jPanels as per no. of properties
            jPanel_arr=new javax.swing.JPanel[total_records];
            System.out.println(total_records);
            
            //Initializing size of string array as per the no. of properties
            arr_names=new String[total_records];
            arr_status=new String[total_records];
            arr_price=new String[total_records];
            arr_type=new String[total_records];
            arr_address=new String[total_records];
            arr_id=new int[total_records];
        }catch(Exception e){
            System.out.println(e);
            
        }
        return total_records;
    }
    
     public void property_details(int price,String location,String search,int code){
        //variables
        int j=0;
        ResultSet rs=null;
        
        //code
        try{
        //Class.forName("com.mysql.cj.jdbc.Driver");
        //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/privatepropertyrentalsystemdb", "shivani", "root");
        con=DBconnection.connect();
        Statement stmt = con.createStatement();

            if(code==0){
                rs=stmt.executeQuery("select Property_name,Status,Rental_price,Property_type,Property_address,Property_id from property;");
            }
            else if(code==1){
                rs=stmt.executeQuery("select Property_name,Status,Rental_price,Property_type,Property_address,Property_id from property where Rental_price < "+price+";");
            }
            else if(code==2){
                rs=stmt.executeQuery("select Property_name,Status,Rental_price,Property_type,Property_address,Property_id from property where Property_address = '"+location+"';");
            }
            else if(code==3){
                 rs=stmt.executeQuery("select Property_name,Status,Rental_price,Property_type,Property_address,Property_id from property where Property_name like '"+search+"%' OR Property_address like '"+search+"%' OR Rental_price like '"+search+"%';");
               
            }
            j=0;
            while(rs.next()){
                arr_names[j]=String.valueOf(rs.getString(1));
                arr_status[j]=String.valueOf(rs.getString(2));
                arr_price[j]=String.valueOf(rs.getString(3));
                arr_type[j]=String.valueOf(rs.getString(4));
                arr_address[j]=String.valueOf(rs.getString(5));
                arr_id[j]=rs.getInt(6);
                j++;
            }
        }catch(Exception e){
            System.out.println(e);
            
        }
    }
     
    public void set_jpanel7(int t){
        
        try{
            //removing already present components from jPanel7
            jPanel7.removeAll();
            jPanel7.revalidate();
            jPanel7.repaint();
                  
            /*if(t==0){
                jPanel7.setBackground(Color.LIGHT_GRAY);
            }
            else{
                jPanel7.setBackground(Color.BLACK);
            }*/
                
            jLabel3.setText(t+" properties found!");
            //Adding labels and button to jpanel
            for(int a=0;a<t;a++){
                 jPanel_arr[a]=new javax.swing.JPanel();
                 jPanel_arr[a].setLayout(new java.awt.GridLayout(0,2,10,10));
                 jPanel_arr[a].setBorder(javax.swing.BorderFactory.createEmptyBorder(20,20,20,20));
                 
                 l_names[a]=new javax.swing.JLabel();
                 l_names[a].setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
                 l_names[a].setText("Name:"+arr_names[a]);
                 //l_names[a].setSize(50,50);
                 jPanel_arr[a].add(l_names[a]);
                                  
                 l_status[a]=new javax.swing.JLabel();
                 l_status[a].setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
                 l_status[a].setText("Rental status:"+arr_status[a]);
                 l_status[a].setSize(50,50);
                 jPanel_arr[a].add(l_status[a]);
                                 
                 l_price[a]=new javax.swing.JLabel();
                 l_price[a].setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
                 l_price[a].setText("Rental price:"+arr_price[a]);
                 l_price[a].setSize(50,50);
                 
                jPanel_arr[a].add(l_price[a]);
             
                 
                 l_type[a]=new javax.swing.JLabel();
                 l_type[a].setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
                 l_type[a].setText("Property type:"+arr_type[a]);
                 l_type[a].setSize(50,50);
                 
                 jPanel_arr[a].add(l_type[a]);
                
                 
                 l_address[a]=new javax.swing.JLabel();
                 l_address[a].setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
                 l_address[a].setText("Location:"+arr_address[a]);
                 l_address[a].setSize(50,50);
                 jPanel_arr[a].add(l_address[a]);
                
                 
                 b_view[a]=new javax.swing.JButton();
                 b_view[a].setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
                 b_view[a].setText("View Property");
                 //b_view[a].setSize(50,50);
                
                 b_view[a].addActionListener(this);
                 jPanel_arr[a].add(b_view[a]);
                 
                 jPanel7.add(jPanel_arr[a]);
                         
            }            
           
            //jpanels need to be revalidated after adding new components dynamically
            jPanel1.revalidate();
            jPanel7.revalidate();
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
    //method to handle the view property event
    public void actionPerformed(ActionEvent e) {
        for(int a=0;a<b_view.length;a++){
            if(e.getSource() == b_view[a]){
                System.out.println(arr_id[a]);
               
                View_property v=new View_property(arr_id[a],userID,userName);
                v.setLocationRelativeTo(null);
                v.setVisible(true);
                v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            }
        }
        
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel usernm;
    // End of variables declaration//GEN-END:variables
}
