/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproject;
import java.awt.event.ItemEvent;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Shivani Shirale
 */
public class Review extends javax.swing.JFrame {

    /**
     * Creates new form Review
     */
    int propertyID=101;
    public Review() {
        initComponents();
    }
    public Review(int newPropertyID)
    {
        propertyID=newPropertyID;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        basePanel = new javax.swing.JPanel();
        customerReviewPanel = new javax.swing.JPanel();
        customerReview = new javax.swing.JLabel();
        comboSortReview = new javax.swing.JComboBox<>();
        sortReview = new javax.swing.JLabel();
        sortedOutputPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedback1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        feedback2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        name3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        feedback3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        propertyImagePanel = new javax.swing.JPanel();
        propertImage = new javax.swing.JLabel();
        writeReview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setBackground(new java.awt.Color(0, 0, 0));
        basePanel.setToolTipText("");

        customerReviewPanel.setBackground(new java.awt.Color(153, 153, 153));

        customerReview.setBackground(new java.awt.Color(0, 51, 204));
        customerReview.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerReview.setText("Customer Reviews");

        comboSortReview.setBackground(new java.awt.Color(0, 51, 204));
        comboSortReview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboSortReview.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top review", "Most recent review" }));
        comboSortReview.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSortReviewItemStateChanged(evt);
            }
        });
        comboSortReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSortReviewActionPerformed(evt);
            }
        });

        sortReview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sortReview.setText("Sort By");

        sortedOutputPanel.setBackground(new java.awt.Color(255, 255, 255));

        name1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        name1.setText("Name");

        feedback1.setEditable(false);
        feedback1.setColumns(20);
        feedback1.setRows(5);
        jScrollPane1.setViewportView(feedback1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        name2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        name2.setText("Name");

        feedback2.setEditable(false);
        feedback2.setColumns(20);
        feedback2.setRows(5);
        jScrollPane2.setViewportView(feedback2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        name3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        name3.setText("Name");

        feedback3.setEditable(false);
        feedback3.setColumns(20);
        feedback3.setRows(5);
        jScrollPane3.setViewportView(feedback3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout sortedOutputPanelLayout = new javax.swing.GroupLayout(sortedOutputPanel);
        sortedOutputPanel.setLayout(sortedOutputPanelLayout);
        sortedOutputPanelLayout.setHorizontalGroup(
            sortedOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sortedOutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortedOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sortedOutputPanelLayout.setVerticalGroup(
            sortedOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortedOutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerReviewPanelLayout = new javax.swing.GroupLayout(customerReviewPanel);
        customerReviewPanel.setLayout(customerReviewPanelLayout);
        customerReviewPanelLayout.setHorizontalGroup(
            customerReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerReviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortedOutputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(customerReviewPanelLayout.createSequentialGroup()
                        .addGroup(customerReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerReview, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(customerReviewPanelLayout.createSequentialGroup()
                                .addComponent(sortReview, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboSortReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        customerReviewPanelLayout.setVerticalGroup(
            customerReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerReviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerReview, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortReview, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSortReview, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortedOutputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        propertyImagePanel.setBackground(new java.awt.Color(153, 153, 153));

        propertImage.setBackground(new java.awt.Color(0, 51, 204));
        propertImage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        propertImage.setText("Property Image");

        writeReview.setBackground(new java.awt.Color(0, 51, 204));
        writeReview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        writeReview.setText("Write Review");
        writeReview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        writeReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout propertyImagePanelLayout = new javax.swing.GroupLayout(propertyImagePanel);
        propertyImagePanel.setLayout(propertyImagePanelLayout);
        propertyImagePanelLayout.setHorizontalGroup(
            propertyImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertyImagePanelLayout.createSequentialGroup()
                .addGroup(propertyImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propertyImagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(propertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(propertyImagePanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(writeReview, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        propertyImagePanelLayout.setVerticalGroup(
            propertyImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertyImagePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(propertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(writeReview, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerReviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(propertyImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerReviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reviews", basePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void writeReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeReviewActionPerformed
        // TODO add your handling code here:
        NewReview n1=new NewReview();
        n1.setVisible(true);
    }//GEN-LAST:event_writeReviewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String selectedItem = comboSortReview.getItemAt(comboSortReview.getSelectedIndex());
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/privatepropertyrentalsystemdb", "shivani", "root");
            Statement st=con.createStatement();
            if(selectedItem.equals("Top review"))
            {
                ResultSet rs=st.executeQuery("select user.user_name,review.description,review.date,review.time,review.property_id from user inner join review on user.user_id=review.user_id group by review.review_id having review.property_id="+propertyID+";");
                //where review.review_id between 501 and 503
                rs.next();
                name1.setText(""+rs.getString("user.user_name"));
                feedback1.setText(""+rs.getString("review.description")+"\n"+rs.getDate("review.date")+"\n"+rs.getTime("review.time"));
                rs.next();
                name2.setText(""+rs.getString("user.user_name"));
                feedback2.setText(""+rs.getString("review.description")+"\n"+rs.getDate("review.date")+"\n"+rs.getTime("review.time"));
                rs.next();
                name3.setText(""+rs.getString("user.user_name"));
                feedback3.setText(""+rs.getString("review.description")+"\n"+rs.getDate("review.date")+"\n"+rs.getTime("review.time"));

                //feedback1.setText("Description added");
            }
            else if(selectedItem.equals("Most recent review"))
            {

                ResultSet rs=st.executeQuery("select user.user_name,review.description,review.date,review.time,review.property_id from user inner join review on user.user_id=review.user_id group by review.review_id having review.property_id ="+propertyID+" order by review.review_id desc;");

                rs.next();
                name1.setText(""+rs.getString("user.user_name"));
                feedback1.setText(""+rs.getString("review.description")+"\n"+rs.getDate("review.date")+"\n"+rs.getTime("review.time"));
                rs.next();
                name2.setText(""+rs.getString("user.user_name"));
                feedback2.setText(""+rs.getString("review.description")+"\n"+rs.getDate("review.date")+"\n"+rs.getTime("review.time"));
                rs.next();
                name3.setText(""+rs.getString("user.user_name"));
                feedback3.setText(""+rs.getString("review.description")+"\n"+rs.getDate("review.date")+"\n"+rs.getTime("review.time"));
            }
        } catch (Exception e)
        {

        }
        //feedback1.setText(comboSortReview.getItemAt(comboSortReview.getSelectedIndex()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboSortReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSortReviewActionPerformed

    }//GEN-LAST:event_comboSortReviewActionPerformed

    private void comboSortReviewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSortReviewItemStateChanged
        // TODO add your handling code here
    }//GEN-LAST:event_comboSortReviewItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Review().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JComboBox<String> comboSortReview;
    private javax.swing.JLabel customerReview;
    private javax.swing.JPanel customerReviewPanel;
    private javax.swing.JTextArea feedback1;
    private javax.swing.JTextArea feedback2;
    private javax.swing.JTextArea feedback3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel propertImage;
    private javax.swing.JPanel propertyImagePanel;
    private javax.swing.JLabel sortReview;
    private javax.swing.JPanel sortedOutputPanel;
    private javax.swing.JButton writeReview;
    // End of variables declaration//GEN-END:variables
}
